### ISSUE TITLE
Improve node parsing

### ISSUE THREAD

**Issue by Zarcix** [Zarcix/TSK200#4]
Currently nodes are parsed in two separate files. There *has* to be a better way to do this. Maybe just one file containing all the info about the tsk program?

- [ ] Is LibConfig viable for this?

**Comment by Zarcix** [comment]
If libconfig, considering something like the blob below. Good since it doesn't have to read file names anymore to parse the node name. Instead, it can use the node name from the nodeList and parsre it from there.

```
programName = "someName";

nodeList = (
    "node1",
    "node2",
    "node3"
);

nodeInstructions = {
    node1 = (
        "MOV ACC ACC",
        "ADD ACC",
        "SUB 10"
    );
    node2 = (
        "MOV 5 UP",
        "MOV UP DOWN"
    );
    node3 = (
    );
};

nodeMapping = {
    node1 = {
        UP = "node2";
        DOWN = "node3";
    };
    node2 = {
        LEFT = "node1";
        RIGHT = "node2";
    }
}
```

**Comment by Zarcix** [comment]
A wrapper program can also be made for this to generate the file dynamically instead of having to type in the things every single time

**Comment by Zarcix** [comment]
For YAML

``` yaml
programName: someName

nodeList:
  - node1
  - node2
  - node3

nodeInstructions:
  node1:
    - MOV ACC ACC
    - ADD ACC
    - SUB 10
  node2:
    - MOV 5 UP
    - MOV UP DOWN
  node3: []

nodeMapping:
  node1:
    UP: node2
    DOWN: node3
  node2:
    LEFT: node1
    RIGHT: node2
```

or

``` yaml
programName: someName

nodeList:
  - node1
  - node2
  - node3

nodeInstructions:
  node1: |
    MOV ACC ACC
    ADD ACC
    SUB 10
  node2: |
    MOV 5 UP
    MOV UP DOWN
  node3: []

nodeMapping:
  node1:
    UP: node2
    DOWN: node3
  node2:
    LEFT: node1
    RIGHT: node2
```
